"""Agregar columna 'imagen_fondo' y 'descripcion' a la tabla 'usuarios'

Revision ID: 766d3170977a
Revises: 
Create Date: 2024-09-27 20:48:14.425861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766d3170977a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('Descripcion', sa.String(length=300), nullable=True))
    op.add_column('usuario', sa.Column('imagen_fonodo', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'imagen_fonodo')
    op.drop_column('usuario', 'Descripcion')
    # ### end Alembic commands ###
